In [1]:
import numpy as np
import os

In [2]:
np.int64(126.5)

126

In [2]:
filename = "vel3D.bin"

In [38]:
# Size of the array
skip = np.fromfile(filename, dtype=np.int32, count=1)

velx = np.fromfile(filename, dtype=np.int8, count=5592405)
vely = np.fromfile(filename, dtype=np.int8, count=5592405)
velz = np.fromfile(filename, dtype=np.int8, count=5592405)

skip2 = np.fromfile(filename, dtype=np.int32, count=1)

print(velx, vely)

#print(stringarr)


16777215
[  0   0   0 ... -95  63   8] [  0   0   0 ... -95  63   8]


In [45]:
with open(filename, "rb") as file:

    skip = np.fromfile(file, dtype=np.int32, count=1)

    stringarr = np.fromfile(file, dtype=np.int8, count=4)

    print(stringarr)
    tag = "".join([str(item) for item in stringarr])

    dumread = np.fromfile(file, dtype=np.int32, count=1)

    print(dumread)

    print(tag)



[-15  61 -79 -14]
[-1074975005]
-1561-79-14


In [62]:
from scipy.io import FortranFile
import numpy as np

f = FortranFile("arepo_out", "r")


header = f.read_reals(np.int32)
pos = f.read_reals(np.double).reshape((3, header[0]))
vels = f.read_reals(np.double).reshape((3, header[0]))
pIDs = f.read_reals(np.double)
pMass = f.read_reals(np.double)
pEnergy = f.read_reals(np.double)


print(np.shape(pos))
print(np.shape(vels))
print(np.shape(pIDs))
print(np.shape(pMass))
print(np.shape(pEnergy))
print(header)


(3, 1093627)
(3, 1093627)
(1093627,)
(1093627,)
(1093627,)
[    1093627           0           0           0           0           0
           0           0           0           0           0           0
           0           0     1093627           0           0           0
           0           0           0           1           0           0
           0           0           0           0           0           0
           0           0     1093627           0           0   -35261186
  1188596348 -2049400832  1131820119           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0]


In [43]:
from scipy.io import FortranFile

ff = FortranFile("vel3D.bin", "r")

v = ff.read_reals()

np.shape(v)

(2097152,)

In [66]:
from scipy.io import FortranFile

f = FortranFile(filename, "r")

velx = f.read_reals().reshape((128,128,128))
vely = f.read_reals()
velz = f.read_reals()


In [3]:
n = np.zeros((2,2,2))

n[0,0,0]

0.0

In [5]:
from turbulence import turbulenceFromFile

velx, vely, velz = turbulenceFromFile(128, "vel3D.bin")

np.dtype(velx[0,0,0])

dtype('float64')

In [18]:
from scipy.io import FortranFile
import numpy as np

f = FortranFile("arepo_out")

h = f.read_reals()
print(h[-1])

p = f.read_reals()
v = f.read_reals()
i = f.read_ints()
m = f.read_reals()
e = f.read_reals()

print(p)
print(v)
print(i)
print(m)
print(e)

0.0
[ 36.47656526  36.47656526  36.47656526 ... 105.57542414  82.37927936
  14.17632017]
[1362.51160248 1362.51160248 1362.51160248 ...    0.            0.
    0.        ]
[     1      2      3 ... 992736 992737 992738]
[2.56865501e-05 2.56865501e-05 2.56865501e-05 ... 1.28435654e-05
 1.28435654e-05 1.28435654e-05]
[1.00567448 1.00567448 1.00567448 ... 2.01134897 2.01134897 2.01134897]


In [8]:
from scipy.io import FortranFile
import numpy as np

f = FortranFile("n100cc_m1000_vir.dat")

h = f.read_reals()
print(h[-1])

p = f.read_reals()
v = f.read_reals()
i = f.read_ints()
m = f.read_reals()
e = f.read_reals()

print(p)
print(v)
print(i)
print(m)
print(e)

0.0
[265.93453979 331.74154663 383.11065674 ... 185.47149658 550.96209717
 254.4418335 ]
[-0.87763613  1.07296634 -0.88174528 ...  0.          0.
  0.        ]
[      1       2       3 ... 2039998 2039999 2040000]
[0.0005     0.0005     0.0005     ... 0.00744674 0.00744674 0.00744674]
[2.68227479 2.68227479 2.68227479 ... 2.68227479 2.68227479 2.68227479]
